[package]
name = "riptide"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
path = "src/lib/lib.rs"

[dependencies]
dirs = "5.0.1"
toml = "0.5.2"
serde = "1.0.136"
serde_derive = "1.0.136"
